name: SCSS Compilation and Deployment

on:
  push:
    branches:
      - main
      - upgrade-bootstrap

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
             sudo apt-get update
             sudo apt-get install cssmin

      - name: Compile SCSS to CSS
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: scss/grayscale.scss
          destination: scss/grayscale.css

      - name: Minify CSS
        run: cssmin -o scss/grayscale.min.css scss/grayscale.css

      - name: Deploy compiled CSS to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: css/grayscale.css
